name: Deploy on Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key-scan: true
          persist-credentials: false

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute remote commands on server
        run: |
          ssh astral-defender.online '
            cd /srv/astral-defender &&
            ls -la &&
            echo Privet
          '
